spring.datasource.url=jdbc:postgresql://localhost:5433/guardrail_db?stringtype=unspecified&options=-c%20TimeZone=UTC
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.redis.host=localhost
spring.redis.port=6380